### ISSUE TITLE
Can't play anything after update

### ISSUE THREAD

**Issue by IsidoreIsou** [YunoHost-Apps/funkwhale_ynh#65]
Hey,
I've just updated from yunohost admin, and now all my play button are gray, and I get this message. Can't play anything anymore. I have this message when I rollover the play button:

> This track is not available in any library you have access to
![](https://framapic.org/xZvnWr80Iiah/DavZ58yCyfQC)

Thanks for any help.

**Comment by Jibec** [comment]
hi, thanks for your report.
Is this album on your server or is it coming from a another one? (federated)
Have you tried to add a new track?

Is the user used an admin or not? If no, can you try using the admin user to see how to behave?

**Comment by IsidoreIsou** [comment]
Hey, thanks for your feedback, I've find a solution, here all the infos I have.

- All albums are on my server, none are playable
- New track upload but is not playable either
- My user is admin
- My library privacy level is: `Privacy level: only me`

Solution:
- If I change to `Privacy level: Everyone on my instance, and my followers`, everything is playable again, everything is back to normal.

After the update, a new library has been created, named `default`. I think I deleted this before. Maybe the issue is related?

**Comment by IsidoreIsou** [comment]
Well there is still a problem, each time I load my fw instance, nothing is playable. Then I have to refresh the page, and everything is. Maybe I should talk about it in the funkwhale forum or git, because it doesn't seems yunohost related, right?

**Comment by EliotBerriot** [comment]
Hi @IsidoreIsou! It's possible that your issue is an upstream bug yes.

To sum it up:

- You upgraded from 0.17 to 0.18
- You log as the admin user
- You have a private library with music that was playable before and its content is now greyed out
- When you change the visibility level of the library from "me" to "instance", tracks are playable again
- When you load the UI in your browser for the first time (e.g after a computer reboot), tracks that are present in this library are disabled, but become playable when you refresh the page

Is that a correct description of your issue here?

> After the update, a new library has been created, named default. I think I deleted this before. Maybe the issue is related?

Maybe.

@Jibec, based on the [upgrade script](https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/scripts/upgrade#L216-L217), you are still running the 0.17 and 0.16 upgrade scripts. That's probably why there is a `default` library being created again for this user (because it was deleted, so the script recreated it).

So you think it could be possible to remove

**Comment by IsidoreIsou** [comment]
Hello @EliotBerriot thanks for your help!

> * You upgraded from 0.17 to 0.18
> * You log as the admin user
> * You have a private library with music that was playable before and its content is now greyed out
> * When you change the visibility level of the library from "me" to "instance", tracks are playable again
> * When you load the UI in your browser for the first time (e.g after a computer reboot), tracks that are present in this library are disabled, but become playable when you refresh the page

100% exactly right.

**Comment by EliotBerriot** [comment]
So I guess we have two issues:

- One issue with the visibility stuff (private library not playale, while instance one is)
- One caching/frontend issue

Would you mind trying to revert your library visibility back to `me` and tell me if tracks are still not playable?

**Comment by IsidoreIsou** [comment]
> Would you mind trying to revert your library visibility back to `me` and tell me if tracks are still not playable?

I just did revert to `only me` and all tracks **are** playable after a browser refresh. Sorry I didn't not target the problem very well actually. 
* So the only issue seems to have to refresh the page, each time I load my instance. If I close my webpage and I reopen it, I have to refresh it so the tracks can be playable.

* Another thing: All tracks in the queue are always playable. No need no refresh for them.

**Comment by llinfrance** [comment]
Hello,

I have the same issue after my upgrade to 0.18.2. Also, reloading the page enable the tracks, so it is not a blocking issue. 

Here the output of the upgrade : 
> sudo yunohost app upgrade funkwhale -u https://github.com/YunoHost-Apps/funkwhale_ynh
Info: Now upgrading app funkwhale…
Warning: 3402 Data dir will not be saved, because backup_core_only is set.
Info: Reload the service nginx
Warning: lsof: WARNING: can't stat() cifs file system /media/Music
Warning:       Output information may be incomplete.
Warning: lsof: WARNING: can't stat() cifs file system /media/Music
Warning:       Output information may be incomplete.
Warning: lsof: WARNING: can't stat() cifs file system /media/Music
Warning:       Output information may be incomplete.
Warning: lsof: WARNING: can't stat() cifs file system /media/Music
Warning:       Output information may be incomplete.
Warning: django-versatileimagefield 1.9 has requirement Pillow<=5.0.0,>=2.4.0, but you'll have pillow 5.4.1 which is incompatible.
Warning: Skipping django-cacheops as it is not installed.
Success! funkwhale has been upgraded
Success! The SSOwat configuration has been generated
Success! Upgrade complete

For info, I was on the testing branch and switch to master. Moreover, all my musics was import in place from a mount hard drive.

As before, I really enjoy funkwhale and its spirit :)
Thank you for your work !

**Comment by Jibec** [comment]
> @Jibec, based on the [upgrade script](https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/scripts/upgrade#L216-L217), you are still running the 0.17 and 0.16 upgrade scripts. That's probably why there is a `default` library being created again for this user (because it was deleted, so the script recreated it).
> 
> So, do you think it could be possible to remove upgrade scripts from previous versions?

Is this question still valid? If the question is: can I run only once the command "python api/manage.py script migrate_to_user_libraries --no-input" and not at every upgrade, yes I can. Can you confirm this is what I should do?

**Comment by IsidoreIsou** [comment]
I am still running `0.18.2` but this issue is gone. Everything is playable without refresh needed. Sorry but I'm not sure what fixed it.
